Translation: measuring_success
opensource-101/the_open_source_way-guidebook-2.0-zh pull request #9
Opened 2021-10-25 01:09 UTC by wgzhao

2021-11-02 12:02 UTC, wgzhao commented
The response  is so slow that I had to close this PR

2021-11-03 17:09 UTC, Cubik65536 commented
> The response is so slow that I had to close this PR

@wgzhao Everyone in this team are busy, no one can promise that we can finish review in a short time, we are still managing to get more time for content review, just be patient please.

2021-11-03 21:44 UTC, KevinZonda requested changes
I have no idea. /cc @Cubik65536

2021-11-03 21:44 UTC, KevinZonda commented on translation/Measuring Success/measuring_success.md
> +在开源之前，衡量一个软件工作的成功与否往往是以严格的财务术语来定义的。一个公司卖出了多少盒软件--是的，多少盒？这笔收入被支持、编写和分发的成本所抵消（同样是盒子），仅此而已。利润就是衡量成功的标准。
```suggestion
在开源之前，衡量一个软件工作的成功与否往往是以严格的财务术语来定义的。一个公司卖出了多少盒软件──是的，多少盒？这笔收入被支持、编写和分发的成本所抵消（同样是盒子），仅此而已。利润就是衡量成功的标准。
```

2021-11-03 21:44 UTC, KevinZonda commented on translation/Measuring Success/measuring_success.md
> +在开源的世界里，情况并不完全如此。首先，虽然存在一些商业成功的开源项目，但这些项目的成功仍然不是严格地与财务状况挂钩的。成功也不是以下载量这个共同的基准来设定的。例如，我们很容易假定，如果一个软件项目有数百万的下载量，那么它就做得非常成功。但是这仅仅只是用户在稳定地消费该软件，并不意味着该项目社区中没有内部问题。依旧可能存在任何因素会使项目停顿下来。相反，有许多非常成功的项目并没有头条新闻和巨大
`依旧可能存在任何因素会使项目停顿下来` is weird.

2021-11-03 21:44 UTC, KevinZonda commented on translation/Measuring Success/measuring_success.md
> +对于开源项目来说，成功不仅仅是用商业或消费方面的指标来衡量的。由于分布式版本控制和协作工具的普及，自由和开源项目的发展变得更加透明。虽然这些工具，如基于 git 的工具，肯定给贡献者带来了把项目放在一起的巨大优势，但另一个好处是，它们也允许对项目的表现进行更有力的定量观察。
`虽然这些工具，如基于 git 的工具，肯定给贡献者带来了把项目放在一起的巨大优势，但另一个好处是，它们也允许对项目的表现进行更有力的定量观察。` is still weird. Coul try think a better word to instead `虽然`.

2021-11-03 21:47 UTC, KevinZonda commented
Apologise to slow CR. Currently I am busier than usual and under extremely high pressure, it may take longer to response you. Apologise again for the inconvenience I caused. :)

2021-11-03 23:32 UTC, Cubik65536 requested changes

2021-11-03 23:32 UTC, Cubik65536 commented on translation/Measuring Success/measuring_success.md
> +在开源之前，衡量一个软件工作的成功与否往往是以严格的财务术语来定义的。一个公司卖出了多少盒软件--是的，多少盒？这笔收入被支持、编写和分发的成本所抵消（同样是盒子），仅此而已。利润就是衡量成功的标准。
而且 `多少盒软件` 其实挺奇怪的，是否可以使用：

```suggestion
在开源之前，衡量一个软件工作的成功与否往往是以严格的财务术语来定义的。一个公司卖出了多少份软件──是的，多少份？这笔收入被支持、编写和分发（同样是多少份）的成本所抵消，仅此而已。利润就是衡量成功的标准。
```

2021-11-03 23:32 UTC, Cubik65536 commented on translation/Measuring Success/measuring_success.md
> +在开源的世界里，情况并不完全如此。首先，虽然存在一些商业成功的开源项目，但这些项目的成功仍然不是严格地与财务状况挂钩的。成功也不是以下载量这个共同的基准来设定的。例如，我们很容易假定，如果一个软件项目有数百万的下载量，那么它就做得非常成功。但是这仅仅只是用户在稳定地消费该软件，并不意味着该项目社区中没有内部问题。依旧可能存在任何因素会使项目停顿下来。相反，有许多非常成功的项目并没有头条新闻和巨大
```suggestion
在开源的世界里，情况并不完全如此。首先，虽然存在一些商业成功的开源项目，但这些项目的成功仍然不是严格地与财务状况挂钩的。成功也不是以下载量这个共同的基准来设定的。例如，我们很容易假定，如果一个软件项目有数百万的下载量，那么它就做得非常成功。但是这仅仅只是用户在稳定地消费该软件，并不意味着该项目社区中没有内部问题。可能会使项目停摆的问题仍然有可能存在。相反，有许多非常成功的项目并没有头条新闻和巨大的人气。
```

2021-11-03 23:32 UTC, Cubik65536 commented on translation/Measuring Success/measuring_success.md
> +- 讨论健康的、参与性社区的形成
```suggestion
- 讨论健康的、参与度高的社区的形成
```

2021-11-03 23:32 UTC, Cubik65536 commented on translation/Measuring Success/measuring_success.md
> +对于开源项目来说，成功不仅仅是用商业或消费方面的指标来衡量的。由于分布式版本控制和协作工具的普及，自由和开源项目的发展变得更加透明。虽然这些工具，如基于 git 的工具，肯定给贡献者带来了把项目放在一起的巨大优势，但另一个好处是，它们也允许对项目的表现进行更有力的定量观察。
Still have to reconsider the translation for this part

2021-11-04 00:52 UTC, wgzhao commented
> Apologise to slow CR. Currently I am busier than usual and under extremely high pressure, it may take longer to response you. Apologise again for the inconvenience I caused. :)

I'm sorry for that,  I take back what I said before.

2021-11-04 00:52 UTC, wgzhao commented on translation/Measuring Success/measuring_success.md
> +对于开源项目来说，成功不仅仅是用商业或消费方面的指标来衡量的。由于分布式版本控制和协作工具的普及，自由和开源项目的发展变得更加透明。虽然这些工具，如基于 git 的工具，肯定给贡献者带来了把项目放在一起的巨大优势，但另一个好处是，它们也允许对项目的表现进行更有力的定量观察。
sure

2021-11-04 01:04 UTC, KevinZonda commented on translation/Measuring Success/measuring_success.md
> +在开源之前，衡量一个软件工作的成功与否往往是以严格的财务术语来定义的。一个公司卖出了多少盒软件--是的，多少盒？这笔收入被支持、编写和分发的成本所抵消（同样是盒子），仅此而已。利润就是衡量成功的标准。
Looks better

2021-11-04 01:05 UTC, KevinZonda commented on translation/Measuring Success/measuring_success.md
> +在开源的世界里，情况并不完全如此。首先，虽然存在一些商业成功的开源项目，但这些项目的成功仍然不是严格地与财务状况挂钩的。成功也不是以下载量这个共同的基准来设定的。例如，我们很容易假定，如果一个软件项目有数百万的下载量，那么它就做得非常成功。但是这仅仅只是用户在稳定地消费该软件，并不意味着该项目社区中没有内部问题。依旧可能存在任何因素会使项目停顿下来。相反，有许多非常成功的项目并没有头条新闻和巨大
LGTM

2021-11-04 01:05 UTC, KevinZonda commented
> > Apologise to slow CR. Currently I am busier than usual and under extremely high pressure, it may take longer to response you. Apologise again for the inconvenience I caused. :)
> 
> I'm sorry for that, I take back what I said before.

Thanks for your understanding. :)

2021-11-04 01:14 UTC, wgzhao commented on translation/Measuring Success/measuring_success.md
> +- 讨论健康的、参与性社区的形成
改成 高参与性，读起来顺口一些

2021-11-04 01:28 UTC, KevinZonda commented
![image](https://user-images.githubusercontent.com/33132228/140242028-759550ed-bdc9-4883-bcfe-d3da2a235a89.png)

Ohhh lao tian ye a, ni kan, fa sheng le shen me?

2021-11-04 01:30 UTC, KevinZonda commented
@wgzhao Actually, you should **NOT** use force push, this will cause all of our reviews out of date and do not work.

2021-11-04 01:31 UTC, wgzhao commented
> 
> Ohhh lao tian ye a, ni kan, fa sheng le shen me?

As a PR commit habit, I squashed multiple commits into one

Do you see the last commit ?

2021-11-04 02:30 UTC, KevinZonda commented
> > Ohhh lao tian ye a, ni kan, fa sheng le shen me?
> 
> As a PR commit habit, I squashed multiple commits into one
> 
> Do you see the last commit ?

Yes, it looks neat to commit, but that can only be bad for us in tracking down problems. And in the meantime, this can be done entirely at merge time, not now.

2021-11-04 02:33 UTC, KevinZonda commented
I'll review it later, it has been 2:33 am in the UK.

+, u should add co author too.

2021-11-04 02:58 UTC, Cubik65536 requested changes
在 CR 过后 Force Push 是个不好的习惯，如果在 CR 之前出现了错误的 commit，FP或许是个方法，但是请不要 CR 过后 FP。FP也**不是**一个让 Pull Request 变得整洁的方法。

另外：如果你使用了其他人的 suggestion，而且手动更改并 commit 了，请记得添加 co-author，这是对别人工作的尊重

2021-11-04 02:58 UTC, Cubik65536 commented on translation/Measuring Success/measuring_success.md
> +在开源之前，衡量一个软件工作的成功与否往往是以严格的财务术语来定义的。一个公司卖出了多少份软件──是的，多少份？这笔收入被支持、编写和分发的成本所抵消（同样是多少份），然后就可以了。利润是衡量成功的标准。
```suggestion
在开源之前，衡量一个软件工作的成功与否往往是以严格的财务术语来定义的。一个公司卖出了多少份软件──是的，多少份？这笔收入被支持、编写和分发（同样是多少份）的成本所抵消，然后就可以了。利润是衡量成功的标准。
```

我觉得原文的 `（同样是多少份）` 代指分发了多少份软件，可以参考

2021-11-04 03:09 UTC, wgzhao commented
> > > Ohhh lao tian ye a, ni kan, fa sheng le shen me?
> > 
> > 
> > As a PR commit habit, I squashed multiple commits into one
> > Do you see the last commit ?
> 
> Yes, it looks neat to commit, but that can only be bad for us in tracking down problems. And in the meantime, this can be done entirely at merge time, not now.

thanks, I got it

2021-11-04 03:09 UTC, wgzhao commented
> I'll review it later, it has been 2:33 am in the UK.
> 
> +, u should add co author too.

OK

2021-11-04 15:29 UTC, Cubik65536 approved these changes
Looks good to me, please look at this @KevinZonda @gh-Devin @LLLgoyour

2021-11-05 23:40 UTC, KevinZonda commented
Sorry, currently I hv no time to CR such thing. /cc @Cubik65536 @LLLgoyour

2021-11-11 13:21 UTC, closed without merging

2021-11-11 16:01 UTC, Cubik65536 commented
感谢你的贡献，我们将会合并你的更改，以后发现瑕疵再做修复。

------

鉴于你已经将你的仓库删除，我将会把你的内容手动添加到本仓库中并添加你为author